### ISSUE TITLE
__pycache__ is tracked?

### ISSUE THREAD

**Issue by laggycomputer** [12944qwerty/Ratchet#1]
Whoa there. Have you considered adding a `.gitignore` for your project? `__pycache__` files are automatically generated by Python at runtime and should never ever be tracked. Try a one-line `.gitignore` at the repo root containing `.py[coa]`.

Also, please write more descriptive commit descriptions.

**Comment by 12944qwerty** [comment]
hmm, i have to do `.py[coa]`? I though `__pycache__/` was fine?

**Comment by laggycomputer** [comment]
In `.gitignore`s, being more specific is always ideal. `__pycache__/` ignores the entire folder, instead of just the files.

If you need the context, Git ignores empty directories.

**Comment by 12944qwerty** [comment]
ok, thx
